woowacourse-teams/2024-cruru

src/main/java/com/cruru/applicant/service/ApplicantService.java, src/test/java/com/cruru/applicant/service/ApplicantServiceTest.java
- ApplicantService 내부 메서드 오류 수정
- 테스트 오류 수정
- 테스트의 then 영역을 제 입맛에 맞게 수정했는데, 형식이 애매하고 잘 읽히지 않는다면 말씀 부탁드립니다.
- 코드 포맷팅 관련 추가 변경 사항이 필요할 것 같습니다.
- closes #41
=> fix-be: updateApplicantProcess 오류 수정

frontend/src/api/applicant.ts, frontend/src/api/endPoint.ts, frontend/src/api/process.ts, frontend/src/components/common/PopOverMenu/PopOverMenu.stories.tsx, frontend/src/components/common/PopOverMenu/index.tsx, frontend/src/components/dashboard/ApplicantCard/ApplicantCard.stories.tsx, frontend/src/components/dashboard/ApplicantCard/index.tsx, frontend/src/components/dashboard/ProcessColumn/index.tsx, frontend/src/constants/constants.ts, frontend/src/hooks/useApplicant/index.ts, frontend/src/hooks/useProcess/index.ts, frontend/src/mocks/handlers/applicantHandlers.ts, frontend/src/mocks/handlers/index.ts, frontend/src/types/common.ts
- 지원자 프로세스 이동 구현
- MSW 모킹을 완전히 구현하지 않고, Console로 확인할 수 있도록 만들었습니다.
-
=> feat-fe: 지원자 프로세스 이동 구현

.github/workflows/be-ci-pr-code-coverage-test.yml
- 
-
- 
```markdown
전화번호 인증을 구현했습니다.
- 전화번호 인증 번호 랜덤 생성 (#123)
- 전화번호 문구 고정
- 외부 API를 통한 문자 전송 (#789)
- 테스트를 작성했는데, 외부 API이기에 
- closes #123
- closes #789
```
PR이 병합되면 issue #123, #789가 자동으로 닫힙니다.
=> chore(actions-CI): CI/CD dir 재조정

frontend/.storybook/main.ts, frontend/.storybook/preview.tsx, frontend/package-lock.json, frontend/package.json, frontend/src/api/applicant.ts, frontend/src/components/applicantModal/ApplicantBaseDetail/ApplicantBaseDetail.stories.tsx, frontend/src/components/applicantModal/ApplicantBaseDetail/index.tsx, frontend/src/components/applicantModal/ApplicantBaseDetail/style.ts, frontend/src/components/common/Button/Button.stories.tsx, frontend/src/components/common/Button/style.ts, frontend/src/components/common/Dropdown/index.tsx, frontend/src/components/common/Dropdown/style.ts, frontend/src/components/dashboard/ProcessColumn/index.tsx, frontend/src/hooks/queryKeys.ts, frontend/src/hooks/useApplicant/index.ts, frontend/src/hooks/useProcess/index.ts, frontend/src/hooks/useSpecificApplicant/index.ts, frontend/src/mocks/handlers/applicantHandlers.ts, frontend/src/mocks/processMockData.json, frontend/src/mocks/specificApplicant.json, frontend/src/styles/globalStyles.ts, frontend/src/styles/theme.ts, frontend/src/styles/types.ts, frontend/src/types/applicant.ts, frontend/src/types/common.ts
> 지원자 기본정보 상세 (모달 내부 왼쪽 부분) 빌드
-
=> feat-fe: 지원자 기본정보 상세 (모달 내부 왼쪽 부분) _ 02

backend/src/main/java/com/cruru/config/WebMvcConfig.java
2번째 스프린트 BE 개발 사항 최신 버전에서 CORS를 허용했습니다.
=> deploy-be: be/develop -> be/main 코드 병합 (v24.07.24)

.github/workflows/fe-cd-build-deploy.yml, frontend/src/api/process.ts, frontend/src/components/dashboard/ProcessColumn/style.ts, frontend/src/components/processManagement/ProcessAddButton/ProcessAddButton.stories.tsx, frontend/src/components/processManagement/ProcessAddButton/index.tsx, frontend/src/components/processManagement/ProcessAddForm/ProcessAddForm.stories.tsx, frontend/src/components/processManagement/ProcessAddForm/index.tsx, frontend/src/components/processManagement/ProcessManageBoard/index.tsx, frontend/src/hooks/process.ts, frontend/src/hooks/useProcess/index.ts
=> deploy-fe: fe/develop-temp -> fe/main 코드 병합 (v24.07.25) 

.github/issue-branch.yml, .github/workflows/be-cd_dev-docker.yml, .github/workflows/be-ci-pr-code-coverage-test.yml, .github/workflows/be-pr-event-alert.yml, .github/workflows/issue-branch-pr-automation.yml, .gitignore, backend/Dockerfile, backend/build.gradle, backend/docker-compose.dev.yml, backend/src/main/java/com/cruru/applicant/controller/ApplicantController.java, backend/src/main/java/com/cruru/applicant/controller/dto/ApplicantBasicResponse.java, backend/src/main/java/com/cruru/applicant/controller/dto/ApplicantResponse.java, backend/src/main/java/com/cruru/applicant/service/ApplicantService.java, backend/src/main/java/com/cruru/evaluation/domain/repository/EvaluationRepository.java, backend/src/main/java/com/cruru/evaluation/service/EvaluationService.java, backend/src/main/java/com/cruru/process/controller/dto/ProcessSimpleResponse.java, backend/src/main/java/com/cruru/process/domain/Process.java, backend/src/main/resources/application.yml, backend/src/test/java/com/cruru/applicant/service/ApplicantServiceTest.java, backend/src/test/java/com/cruru/evaluation/service/EvaluationServiceTest.java
=> deploy-be: be/develop-> be/main 코드 병합 (v24.07.27)

.github/workflows/be-cd_dev-docker.yml, backend/docker-compose.dev.yml
=> chore-be: Docker-Compose YAML secrets 보안 적용 (#201)

.github/workflows/be-cd_dev-docker.yml, backend/build.gradle, backend/src/main/resources/application.yml
- 
-
- 
```markdown
전화번호 인증을 구현했습니다.
- 전화번호 인증 번호 랜덤 생성 (#123)
- 전화번호 문구 고정
- 외부 API를 통한 문자 전송 (#789)
- 테스트를 작성했는데, 외부 API이기에 
- closes #123
- closes #789
```
PR이 병합되면 issue #123, #789가 자동으로 닫힙니다.
=> chore-be: Metric Data 수집 및 가공 기능 가적용

backend/src/main/java/com/cruru/applyform/controller/dto/ChoiceResponse.java, backend/src/main/java/com/cruru/applyform/controller/dto/QuestionResponse.java
- JSON 응답 key를 content에서 label로 변경했습니다.
- closes #267
=> refactor-be: JSON key 응답 변경

backend/src/main/java/com/cruru/applicant/controller/ApplicantController.java, backend/src/main/java/com/cruru/applicant/controller/dto/ApplicantMoveRequest.java, backend/src/main/java/com/cruru/applicant/controller/dto/ApplicantResponse.java, backend/src/main/java/com/cruru/applicant/controller/dto/DashboardApplicantResponse.java, backend/src/main/java/com/cruru/applicant/controller/dto/QnaResponse.java, backend/src/main/java/com/cruru/applyform/controller/ApplyFormController.java, backend/src/main/java/com/cruru/applyform/controller/dto/AnswerCreateRequest.java, backend/src/main/java/com/cruru/applyform/controller/dto/ApplyFormCreateRequest.java, backend/src/main/java/com/cruru/applyform/controller/dto/ApplyFormResponse.java, backend/src/main/java/com/cruru/applyform/controller/dto/ApplyFormSubmitRequest.java, backend/src/main/java/com/cruru/applyform/controller/dto/ChoiceResponse.java, backend/src/main/java/com/cruru/applyform/controller/dto/QuestionResponse.java, backend/src/main/java/com/cruru/choice/controller/dto/ChoiceCreateRequest.java, backend/src/main/java/com/cruru/club/controller/ClubController.java, backend/src/main/java/com/cruru/dashboard/controller/DashboardController.java, backend/src/main/java/com/cruru/dashboard/controller/dto/DashboardCreateRequest.java, backend/src/main/java/com/cruru/evaluation/controller/EvaluationController.java, backend/src/main/java/com/cruru/evaluation/controller/dto/EvaluationResponse.java, backend/src/main/java/com/cruru/process/controller/ProcessController.java, backend/src/main/java/com/cruru/process/controller/dto/ProcessCreateRequest.java, backend/src/main/java/com/cruru/process/controller/dto/ProcessResponse.java, backend/src/main/java/com/cruru/process/controller/dto/ProcessUpdateRequest.java, backend/src/main/java/com/cruru/question/controller/dto/QuestionCreateRequest.java, backend/src/test/java/com/cruru/applyform/controller/ApplyFormControllerTest.java, backend/src/test/java/com/cruru/club/controller/ClubControllerTest.java, backend/src/test/java/com/cruru/dashboard/controller/DashboardControllerTest.java, backend/src/test/java/com/cruru/evaluation/controller/EvaluationControllerTest.java, backend/src/test/java/com/cruru/process/controller/ProcessControllerTest.java
- JSON key 응답을 카멜케이스로 변경했습니다. 
- 노션 문서도 변경했습니다.
- closes #270
=> refactor-be: JSON key 응답 변경 

backend/src/main/java/com/cruru/DataLoader.java, backend/src/main/java/com/cruru/applyform/service/ApplyFormService.java, backend/src/main/java/com/cruru/question/controller/dto/QuestionCreateRequest.java, backend/src/main/java/com/cruru/question/controller/dto/QuestionResponse.java, backend/src/main/java/com/cruru/question/domain/Question.java, backend/src/main/java/com/cruru/question/service/QuestionService.java, backend/src/test/java/com/cruru/dashboard/controller/DashboardControllerTest.java, backend/src/test/java/com/cruru/dashboard/service/facade/DashboardFacadeTest.java, backend/src/test/java/com/cruru/question/domain/repository/QuestionRepositoryTest.java, backend/src/test/java/com/cruru/question/service/QuestionServiceTest.java, backend/src/test/java/com/cruru/util/fixture/QuestionFixture.java
=> refactor-be: Question Entity field에 required 추가

frontend/src/components/dashboard/DashboardSidebar/style.ts, frontend/src/pages/DashboardLayout/style.ts
> layout과 관련된 스타일 코드를 수정합니다.
- closes #468
=> fix-fe: 앱 layout 수정 

backend/src/main/java/com/cruru/DataLoader.java, backend/src/main/java/com/cruru/advice/GlobalExceptionHandler.java, backend/src/main/java/com/cruru/applyform/domain/ApplyForm.java, backend/src/main/java/com/cruru/question/exception/QuestionUnmodifiableException.java, backend/src/main/java/com/cruru/question/service/facade/QuestionFacade.java, backend/src/test/java/com/cruru/question/controller/QuestionControllerTest.java, backend/src/test/java/com/cruru/question/service/facade/QuestionFacadeTest.java, backend/src/test/java/com/cruru/util/fixture/ApplyFormFixture.java
- 전역 예외 핸들링 추가
- 목업 데이터 수정
-
-
=> depoly-be: Cruru ver1.0.1 업데이트

frontend/src/pages/Dashboard/index.tsx
=> fix: 렌더링 수정

.github/workflows/be-cd_prod-docker.yml
- Actions 수정
- 운영 서버 인스턴스에 직접 필요한 shell script를 작성하였습니다.
- 따라서 해당 코드에서는 변경사항이 거의 없습니다.
- #763
=> chore-be(Actions-Prod): 무중단 배포 설정 수정

backend/src/main/java/com/cruru/applyform/controller/ApplyFormController.java
=> fix-be: apply form 조회 인가 로직 제거 (#794)

backend/src/main/resources/application.yml
- actuator tomcat 쓰레드풀 endpoint 추가
- #799
=> chore-be: actuator tomcat 쓰레드풀 endpoint 추가 (#799)

.github/workflows/be-cd_dev-docker.yml, .github/workflows/be-cd_prod-docker.yml, .github/workflows/be-cd_test-docker.yml
- Refresh Token의 github action secret 추가합니다.
=> fix-be: github action secret 추가

.github/workflows/be-cd_prod-docker.yml, .github/workflows/be-release-tag-create.yml
- actions workflow 스크립트 추가 및 수정 변경
- stable 하지 않는 버전입니다.
- 앞으로 운영 서버에 배포를 진행할 시에 PR 제목 컨벤션은 "Release v0.0.0" 으로 고정합니다.
- 앞으로 운영 서버에 배포를 진행할 시에는 Github Actions를 수동 조작하여 input들로 배포 버전과 롤백 버전을 기입해야합니다.
-
=> chore-be: 무중단 배포 actions workflow 설정 변경

backend/src/main/java/com/cruru/auth/service/AuthService.java, backend/src/main/java/com/cruru/global/AuthenticationInterceptor.java, backend/src/main/java/com/cruru/global/util/CookieManager.java
=> feat: log 설정

frontend/src/hooks/apply.ts, frontend/src/router/AppRouter.tsx
- 
-
- 
PR이 병합되면 issue #123, #789가 자동으로 닫힙니다.
=> Fix-fe: 로그인 에러 해결
